### ISSUE TITLE
(Bug/Suggestion) Items get Smelted with Silk Touch

### ISSUE THREAD

**Issue by Ju999** [achedon12/AutoSmelter#1]
Hey, thanks for your amazing plugin! I have a request, wich might make the plugin even better.
So currently, any item that gets mined will instantly be smelted. My suggestion is, that if theres an Silk Touch enchantement on the tool, the item will not get smeltet (maybe turnable on/off in config). If this is possible, it would be a great addition to the plugin!
Thanks and a good day!

**Comment by achedon12** [comment]
Ow ! Of course ! I'm just waiting for the publishing on poggit and after i can do it !
